
function [wmhprob_dat,wmhmask_dat] = cns2_wmh_ud_postproc_classification (cns2param,flair,t1,i)

curr_cmd = mfilename;

fprintf ('%s : start classification for %s.\n', curr_cmd, cns2param.lists.subjs{i,1});


% 1st-level clusters
% ++++++++++++++++++
[lv1clstrs_dat,cns2param] = cns2_wmh_ud_postproc_classification_1stlvclstrs (cns2param, ...
																			 flair, ...
																			 fullfile (cns2param.dirs.subjs, ...
																			 		   cns2param.lists.subjs{i,1}, ...
																			 		   'ud', ...
																			 		   'postproc', ...
																			 		   'lv1clstrs.nii'), ...
																			 i);
% 2nd-level clusters
% ++++++++++++++++++
lv2clstrs_struct = cns2_wmh_ud_postproc_classification_2ndlvclstrs (cns2param, ...
																    lv1clstrs_dat, ...
																    spm_vol(flair), ...
																    fullfile (cns2param.dirs.subjs, ...
																    		  cns2param.lists.subjs{i,1}, ...
																    		  'ud', ...
																    		  'postproc', ...
																    		  'lv2clstrs.nii'), ...
																    i);
% extract features
% ++++++++++++++++
f_tbl = cns2_wmh_ud_postproc_classification_extFeatures (cns2param, ...
														 flair, ...
														 t1, ...
														 lv2clstrs_struct, ...
														 i);

% predict
% +++++++++++++++
mdl = loadLearnerForCoder(fullfile (cns2param.dirs.cns2, ...
									'wmh', ...
									'cns2_wmh_ud_postproc_classification_knnMdl.mat'));
[wmhprob_dat, wmhmask_dat] = cns2_wmh_ud_postproc_classification_predict   (cns2param,...
																			lv2clstrs_struct,...
																			f_tbl,...
																			mdl,...
																			spm_vol(flair),...
																			i);


