function wrflair_lv1clstrs_dat = cns2_wmh_ud_classification_1stlvclstrs (cns2param, ...
																		 wrflair_brn_dat, ...
																		 wrflair_brn_hdr, ...
																		 idx)
curr_cmd = mfilename;
% volume segmentation using k-means (1st-level clusters)
if cns2param.exe.verbose
	fprintf ('%s : generating %s''s 1st-level clusters.\n', curr_cmd, cns2param.lists.subjs{idx,1});
end

wrflair_lv1clstrs_dat = imsegkmeans3 (single(wrflair_brn_dat), ...
									  cns2param.classification.ud.k4kmeans, ...
									  'NormalizeInput', true);

% write out k-means clusters (1st-level clusters)
if  ~cns2param.exe.save_dskspc
	if cns2param.exe.verbose
		fprintf ('%s : writing %s''s 1st-level clusters.\n', curr_cmd, cns2param.lists.subjs{idx,1});
	end
	cns2_scripts_writeNii (cns2param, ...
						   wrflair_brn_hdr, ...
						   wrflair_lv1clstrs_dat, ...
						   fullfile (cns2param.dirs.subjs, cns2param.lists.subjs{idx,1}, 'wrflair_lv1clstrs.nii'));
end