function cns2param = cns2_wmh_ud_cns2param (cns2param, ...
											lv1clstMethod, ...
										    k4kmeans, ...
										    n4superpixel, ...
										    k4knn, ...
										    probthr, ...
										    extSpace, ...
										    pvmag, ...
										    sizthr);

% classification
% +++++++++++++++++++++++++++++++++++++++++++++
cns2param.classification.ud.lv1clstr_method = lv1clstMethod;
cns2param.classification.ud.k4kmeans        = k4kmeans;
cns2param.classification.ud.n4superpixel    = n4superpixel;
cns2param.classification.ud.k4knn           = k4knn;
cns2param.classification.ud.probthr         = probthr;
cns2param.classification.ud.ext_space       = extSpace;


% quantification
% ++++++++++++++++++++++++++++++++++++++++++
cns2param.quantification.ud.pvmag  = pvmag;  % distance from lateral ventricle - used to define PVWMH and DWMH.
cns2param.quantification.ud.sizthr = sizthr; % cut-off in number of voxels between punctuate, focal, medium, and confluent